// contacts
export const WECHAT_CONTACT_MAIN_SET = 'WECHAT_CONTACT_MAIN_SET';
export const WECHAT_CONTACT_GET_CONTACTER = 'WECHAT_CONTACT_GET_CONTACTER';

// chats
export const WECHAT_CHAT_MAIN_SET = 'WECHAT_CHAT_MAIN_SET';

// self
export const WECHAT_SELF_MAIN_SET = 'WECHAT_SELF_MAIN_SET';
