// contacts
export const WECHAT_CONTACT_MAIN_SET = 'WECHAT_CONTACT_MAIN_SET';
export const WECHAT_CONTACT_GET_CONTACTER = 'WECHAT_CONTACT_GET_CONTACTER';
export const WECHAT_CONTACT_FETCH_CONTACTS = 'WECHAT_CONTACT_FETCH_CONTACTS';
export const WECHAT_CONTACT_FETCH_OFFICIAL_ACCOUNTS = 'WECHAT_CONTACT_FETCH_OFFICIAL_ACCOUNTS';

// new friends
export const WECHAT_CONTACT_FETCH_NEW_FRIENDS = 'WECHAT_CONTACT_FETCH_NEW_FRIENDS';

// chats
export const WECHAT_CHAT_MAIN_SET = 'WECHAT_CHAT_MAIN_SET';
export const WECHAT_CHAT_FETCH_CHATS = 'WECHAT_CHAT_FETCH_CHATS';

// self
export const WECHAT_SELF_MAIN_SET = 'WECHAT_SELF_MAIN_SET';
export const WECHAT_SELF_FETCH_PERSONAL = 'WECHAT_SELF_FETCH_PERSONAL';

// add friends
export const WECHAT_ADD_FRIEND_MAIN_SET = 'WECHAT_ADD_FRIEND_MAIN_SET';
export const WECHAT_ADD_FRIEND_SEARCH_FRIEND = 'WECHAT_ADD_FRIEND_SEARCH_FRIEND';

// album
export const WECHAT_FETCH_MOMENTS = 'WECHAT_FETCH_MOMENTS';
